// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNV8BZbdDMoomEcZwXtqQJQldHs4IkRoM',
    appId: '1:137156002074:web:7151db3de95f80ded6eca3',
    messagingSenderId: '137156002074',
    projectId: 'modemart-21c4e',
    authDomain: 'modemart-21c4e.firebaseapp.com',
    storageBucket: 'modemart-21c4e.firebasestorage.app',
    measurementId: 'G-LNQ3NDLE70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpmFUbi1CtBeIzZRUVBnRYNM4sxqgD6K8',
    appId: '1:137156002074:android:3ae30259d6e91ae3d6eca3',
    messagingSenderId: '137156002074',
    projectId: 'modemart-21c4e',
    storageBucket: 'modemart-21c4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4nJNvjIgTRXS0eVEaXdHJ4WAHXyaPTOs',
    appId: '1:137156002074:ios:b8f1cf3e1fe7980fd6eca3',
    messagingSenderId: '137156002074',
    projectId: 'modemart-21c4e',
    storageBucket: 'modemart-21c4e.firebasestorage.app',
    iosBundleId: 'com.OnoPunpun.modemart',
  );
}
